<a href="https://colab.research.google.com/github/iamVedanta/pytorch-basics/blob/main/Tensor_math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

TENSOR MATH OPERATIONS


*   Add, Subtract, multiply, divide, remaiders n exoibebts
*   shorthand and longhand
* Reassignment



In [1]:
import torch
import numpy as np


In [2]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [3]:
#Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [5]:
#Addition longhand
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [6]:
#Subraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [7]:
#Sub Function
torch.sub(tensor_b,tensor_a)

tensor([4, 4, 4, 4])

In [8]:
#multiplciation
tensor_a*tensor_b

tensor([ 5, 12, 21, 32])

In [9]:
#Mul longhand
torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [10]:
#Division
tensor_a/tensor_b

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [11]:
#Div Long
torch.div(tensor_b,tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [12]:
#Remainder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [13]:
#remainder longhand
torch.remainder(tensor_b,tensor_a)


tensor([0, 0, 1, 0])

In [14]:
#Exponents / power
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [15]:
#another way to longhand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [16]:
#ressassingment
tensor_a+ tensor_b

tensor([ 6,  8, 10, 12])

In [17]:
tensor_a

tensor([1, 2, 3, 4])

In [19]:
#tensor_a = tensor_a + tensor_b
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [21]:
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])